name: 'bee-observe'
services:
  mongo:
    image: mongo:7
    ports:
      - '${DATABASE_EXPOSED_PORT:-27019}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    ports:
      - '${REDIS_EXPOSED_PORT:-6380}:6379'
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5
  mlflow:
    image: bitnami/mlflow:2.14.1
    ports:
      - '${MLFLOW_EXPOSED_PORT:-8080}:8080'
    entrypoint:
      [
        '/bin/bash',
        '-c',
        '/entrypoint.sh && mlflow server --app-name basic-auth --host 0.0.0.0 --port 8080'
      ]
    security_opt:
      - 'label=disable'
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
