name: Deployment
on:
  push:
    branches: ['main']
jobs:
  deploy:
    name: Deploy via Travis
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: 'Install Travis CLI'
        run: gem install travis --no-document
      - name: 'Trigger rebuild'
        run: travis restart --api-endpoint ${{ vars.TRAVIS_ENDPOINT }} --token ${{ secrets.TRAVIS_ACCESS_TOKEN }} --repo ${{ vars.TRAVIS_REPO }} ${{ vars.TRAVIS_BUILD }}